apiVersion: v1
kind: ConfigMap
metadata:
  name: glowroot-configmap
data:
  # Each glowroot instance can use the cassandra instance in the same pod; minimising inter-node 
  # communication.
  glowroot-central.properties: |
    cassandra.contactPoints=127.0.0.1
    jgroups.configurationFile=jgroups-dns.xml
    jgroups.localPort=7800
    jgroups.password=somepassword
  # Use DNS_PING as that works with kubernetes. Otherwise this is the same as the packaged 
  # jgroups-tcp.xml provided with glowroot
  jgroups-dns.xml: |
    <!-- based on https://github.com/belaban/JGroups/blob/JGroups-4.0.3.Final/conf/tcp.xml -->
    <config xmlns="urn:org:jgroups"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">

      <TCP bind_addr="${jgroups.localAddress}"
           bind_port="${jgroups.localPort}"
           recv_buf_size="${jgroups.recvBufSize:130k}"
           send_buf_size="${jgroups.sendBufSize:130k}"
           max_bundle_size="64K"
           sock_conn_timeout="300"
           thread_pool.min_threads="${jgroups.minThreads:0}"
           thread_pool.max_threads="${jgroups.maxThreads:20}"
           thread_pool.keep_alive_time="30000" />
      <dns.DNS_PING
                dns_query="glowroot-svc.{{ .Release.Namespace }}.svc.cluster.local" />
      <MERGE3  min_interval="10000"
               max_interval="30000" />
      <FD_SOCK />
      <FD timeout="3000" max_tries="3" />
      <VERIFY_SUSPECT timeout="1500" />
      <BARRIER />
      <pbcast.NAKACK2 use_mcast_xmit="false"
                      discard_delivered_msgs="true" />
      <UNICAST3 />
      <pbcast.STABLE desired_avg_gossip="50000"
                     max_bytes="4M" />
      <SASL mech="DIGEST-MD5"
            server_name="glowroot"
            client_callback_handler_class="org.glowroot.central.SaslCallbackHandler"
            server_callback_handler_class="org.glowroot.central.SaslCallbackHandler" />
      <pbcast.GMS print_local_addr="false"
                  join_timeout="${jgroups.joinTimeout:2000}" />
      <MFC max_credits="2M"
           min_threshold="0.4" />
      <FRAG2 frag_size="60K" />
      <pbcast.STATE_TRANSFER />
    </config>
